CREATE TABLE IF NOT EXISTS users_website (
  id INT NOT NULL AUTO_INCREMENT,
  discord_id VARCHAR(32) NOT NULL,
  username VARCHAR(100) NOT NULL,
  avatar VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_discord_id (discord_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
